package br.com.xavier.graphs.events.enums;

public enum GraphEventType {
	
	//XXX NODE EVENTS TYPES
	
	//NODE OPERATIONS
	BEFORE_NODE_ADD,
	AFTER_NODE_ADD,
	BEFORE_NODE_REMOVE,
	AFTER_NODE_REMOVE,
	BEFORE_NODE_CHANGE,
	AFTER_NODE_CHANGE,
	
	//XXX EDGE EVENTS TYPES
	
	//NODE OPERATIONS
	BEFORE_EDGE_ADD,
	AFTER_EDGE_ADD,
	BEFORE_EDGE_REMOVE,
	AFTER_EDGE_REMOVE,
	BEFORE_EDGE_CHANGE,
	AFTER_EDGE_CHANGE;
}
